---
version: '3.9'
services:
  tiger:
    build:
      context: ./docker
      args: 
        # 通过环境变量传入， export UID=$(id --user) GID=$(id --group)
        - UID
        - GID
    command:
      - /sbin/init
    volumes: 
        - ./:/tiger
    working_dir: /tiger
